ENVIRONMENT:
  MAX_EPISODE_STEPS: 512
  SCENE: "none"
SIMULATOR:
  TYPE: Sim-v0
  ACTION_SPACE_CONFIG: "v2" # v0: stop, forward, left, right; v1: stop, forward, left, right, up, down; v2: forward, left, right
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 30 # left and right action
  SEED: -1
  TILT_ANGLE: 10 # up and down
  AGENT_0:
    SENSORS: ['RGB_SENSOR'] # don't need semantic labels for exploration policy
    HEIGHT: 0.8
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    POSITION: [0, 0.8, 0]